### ISSUE TITLE
Country feature does not show real country

### ISSUE THREAD

**Issue by Aeroverra** [openproxyspace/unfx-proxy-checker#20]
When I load in a large list of proxies from a provider it only shows the country of the server ip rather than the actual country of origin based off the real exit node. For example a checked list will only show all in one country despite the actual public facing ips being from many countries of origin.  
![image](https://user-images.githubusercontent.com/3579482/57409057-47da0300-71b5-11e9-8992-ef1524b4bd5e.png)

**Comment by relloccate** [comment]
Project uses public geoIP lite database, if you can, you can buy enterprise for $1360 year. How you can check IPs at only client side?

'the actual country of origin based' - Your Ips 100% contain only EU (Netherlands/France). Many GeoIP providers detect the same.

**Comment by relloccate** [comment]
From maxmind site:
GeoLite2 databases are free IP geolocation databases comparable to, but less accurate than.

IP Geolocation Usage
IP geolocation is inherently imprecise. Locations are often near the center of the population. Any location provided by a GeoIP database should not be used to identify a particular address or household.

Use the Accuracy Radius as an indication of geolocation accuracy for the latitude and longitude coordinates we return for an IP address. The actual location of the IP address is likely within the area defined by this radius and the latitude and longitude coordinat

**Comment by Aeroverra** [comment]
Let me clarify. My list of proxies looks like this.  
143.57.34.221:20003
143.57.34.221:20004
143.57.34.221:20005

Same ip different ports but all of them Link to another node. In other words they are sometimes called back connect proxies. The back connect server is in France, the end ips are not.

**Comment by Aeroverra** [comment]
I have taken the time to read it again, and I understand it a bit more. I believe you are saying to use the api that would perform this feature would cost money. However You shouldn't need to do this, you could easily grab the ip via connecting to the proxy and connecting to an api. example: http://checkip.amazonaws.com/ is free. Taking the ip from that you could compare it to the SQLite database.

**Comment by relloccate** [comment]
About:
143.57.34.221:20003
143.57.34.221:20004
143.57.34.221:20005

Just filter through: https://openproxy.space/filter, checker has no feature (filter only unique IPs), at current time.

About other:
You saying about distorting proxies. This is real country of IP, because checks only entry IP, not out. This is different things. Need parse forwarded IPs chain and check latest IP at country, checker has no this feature, g.

**Comment by kolet** [comment]
@assnctr 
hi, sorry for bumping it up.
first of all thanks for the damn great piece of software!
second , i am having the same issue, i was about to open a thread but saw this so i am bumping it up.
let me clarify  what he ment (and what i have)
this ip 143.57.34.221 is just a relay. 
the port will determine what the end node will be.
for example.
143.57.34.221 = USA , BUT
143.57.34.221 port 50000 will send u to ITALY
however 143.57.34.221 on port 50001 will send u to UK
and so on.
lots of proxy services works like this.

since UNFX proxy check DO connect to these socks ip/servers (to see if they are availble/alive) , by connecting to them.
next check should be to see what the end node is, take for example this site. https://ifconfig.co/country
a simple fetch with the socks ip&port to https://ifconfig.co/country will determine which country u really received.
if u enter https://ident.me  manually with socks4/5 u will receive the endip


i was wondering,
on judge, there is a regex for this site (https://ident.me) to find the result ip,
when the result is being received, what actually is being done ? do the unfx proxy checker resolve the country from some where else ? (because if it do, all i wrote in the above is useless if its already supported, but it seems to me it does not resolve the country from the end ip.) if it does, where can i find the result of the regex|?

**Comment by kolet** [comment]
@Aeroverra so,
i found a way to do that,
i spoke with @assnctr  and unfortunately he dont want to add this little feature, which is a big plus to this software.
however, i found a way to do that myself.
u just need to find an domain that send back the country the end node using.
i have tried multiple domains, however it seems that some domains blocks the proxy ips.
i've some research and i found this.
http://extreme-ip-lookup.com/csv/
add this domain to a judge , and put a filter on it. (regex)
meaning if the REGEX is NOT true it will show it as offline,
in my case i wanted to know which end node is a certain country for example france.
so as a string i put france, if the server response does not contain france it will show it as offline, so ONLY server respond with france will show as online note that other port etc, might work properly . but that the filter/regex does.

**Comment by relloccate** [comment]
May be later.
