### ISSUE TITLE
Limit on Amount of Proxies inputted? 

### ISSUE THREAD

**Issue by NiceHacksDude** [openproxyspace/unfx-proxy-checker#9]
Hello! Thanks so much for creating this amazing tool, yet need some help! I try to load around 400,000 proxies yet once I begin checking it reduces it down to something like 45,000. Is there a certain setting that might be causing this? Thanks so much for the help! 

Also my max time out seems to not set, it will keep like 500,000ms timeouts when I set the limit to 10,000

Side Note: Little suggestion, would love a dark mode! 😄

**Comment by relloccate** [comment]
Hi, thanks dude.

Proxy checker was focused on small proxy lists. And these lags on "Load from txt" or paste from keyboard events because of hard to render. I'm adapt checker in next patch for large proxy lists. Later, i have no time for this.

Also i fix timeout:
Timeout is floating - 10.000ms for sonnect to socket + gives 10.000ms to load response, Total max takes time: around 20.000ms.
I think socket connection has issues, doesn't breaks after reach limit.

Yes, think light bulb toggler for change the theme to dark would be nice.
But, yet again, i have no time, g.

**Comment by NiceHacksDude** [comment]
> Hi, thanks dude.
> 
> Proxy checker was focused on small proxy lists. And these lags on "Load from txt" or paste from keyboard events because of hard to render. I'm adapt checker in next patch for large proxy lists. Later, i have no time for this.
> 
> Also i fix timeout:
> Timeout is floating - 10.000ms for sonnect to socket + gives 10.000ms to load response, Total max takes time: around 20.000ms.
> I think socket connection has issues, doesn't breaks after reach limit.
> 
> Yes, think light bulb toggler for change the theme to dark would be nice.
> But, yet again, i have no time, g.

No worries! Thanks for getting back to me, looking forward to the updates once you have time! Thanks again!

**Comment by usaflees** [comment]
I absolutely 100% agree with a “dark” mode!  Text adjustable in any way?

**Comment by relloccate** [comment]
Dark mode soon.

**Comment by relloccate** [comment]
May be new features:
Smart protocols checking (if you check at all protocols), for reduce bandwidth usage.
And cluster mode, for split payload by all CPU cores. Amount of cores * threads, will fastest checking. But need super bandwidth   for exclude potential too much bad checks (fallbacks from socket).
